# Generated by Django 3.2.4 on 2021-06-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(default=None, max_length=500, null=True)),
                ('completed', models.BooleanField(default=None, null=True)),
                ('order', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
